# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "AppChallenge.xcworkspace", scheme: "AppChallenge Debug")
  end

  desc "Runs all the tests"
  lane :tests do
    scan(clean: true, code_coverage: true, scheme: "AppChallenge Debug")
  end

  desc "Runs Coverage"
  lane :coverage do
   slather(scheme: "AppChallenge Debug", workspace: "AppChallenge.xcworkspace", html: true, show: true)
  end

end
